### ISSUE TITLE
Script task with DELETE request that return 204

### ISSUE THREAD

**Issue by paed01** [effektif/effektif#22]
Hi. I'm not sure that this is the proper channel for your excellent service app.effektif.com, but I'll make a try.

I have a script task that makes a DELETE call to a service. The service responds with 204 (No content) and the script task hangs!? Since I also have control over the service where the call is directed I changed the response code to 200. And now everything work fine. But it would, imho, be more proper REST if I could use 204. Is it any special reason why this doesn't work?

**Comment by hilton** [comment]
Hi, the correct support channel is the _Send Feedback_ menu item in the app; I’ll pass this one on for you.

I can reproduce this, using [Mocky](http://www.mocky.io/) to generate an HTTP 204 response, with the following script:

```
request('http://www.mocky.io/v2/556c028cc7c1599106d0e172',
	function (error, response, body) {
	    console.log(response.statusCode);
	}
);
```

The result of running the script test in the process editor is:

>  Timeout exceeded after 30 seconds
> Test execution failed at 09:00:48

**Comment by frontendphil** [comment]
And for future problem you can find the feedback form right in your user menu in the upper right corner of the application.

**Comment by paed01** [comment]
Thank you for the swift response. I also found the user guide! The app is rather self-explanatory so I havn't needed it before, but still it's good to know. :)

**Comment by frontendphil** [comment]
@paed01 unfortunately I cannot reproduce this error. Neither locally nor on our production system. Can you maybe give me a short outline of the script your trying to run?

**Comment by paed01** [comment]
I have a REST-service that accepts DELETE requests.

When I make the delete call to the service from an effektif script task, like this:
```javascript
var options = {
  method: 'DELETE',
  url: 'http://example.com/api/arbitary'
};

request(options, function(err, response, body) {
  // never reached - timeout
  console.log(err, response, body);
});
```

The REST-service reports that the call has been made and responds with statusCode 204. But the script task times out, as in hiltons comment.

**Comment by frontendphil** [comment]
I could only reproduce this behaviour when I configure an endpoint that returns a status code of 204 but __does__ content in the response body. Can you please check that the body of your response is empty?

**Comment by paed01** [comment]
Good point in checking the response of the delete request, it is:
```
HTTP/1.1 204 No Content
Server: Cowboy
Content-Length: 0
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
Date: Fri, 05 Jun 2015 06:32:14 GMT
Via: 1.1 vegur
```
> To make sure we talk about the same thing - I'm using script tasks in a process hosted at https://app.effektif.com.
