### ISSUE TITLE
ScriptTask not working

### ISSUE THREAD

**Issue by jblankendaal** [effektif/effektif#24]
When trying to use the (to be abandoned) ScriptTask I get an error message with this piece of code:

    public static void main(String[] args) {
        try {

            // Create a workflow

            ExecutableWorkflow workflow = new ExecutableWorkflow()
                    .sourceWorkflowId("Server test workflow")
                    .variable("n", new TextType())
                    .variable("m", new TextType())
                    .activity("s", new ScriptTask()
                            .script("message = 'Hello ' + name;")
                            .scriptMapping("name", "n")
                            .scriptMapping("message", "m"));

            final String url = "http://localhost:9999/";

            ClientConfig clientConfig = new ClientConfig();
            JsonStreamMapper jsonStreamMapper = new JsonStreamMapper();
            clientConfig.register(new EffektifJsonProvider(jsonStreamMapper));
            Client client = ClientBuilder.newClient(clientConfig);

            WebTarget target = client.target(url);
            Deployment deployment =
                    target.path("deploy").request()
                            .accept(MediaType.APPLICATION_JSON)
                            .post(Entity.entity(workflow, MediaType.APPLICATION_JSON))
                            .readEntity(Deployment.class);

            System.out.println("Deployed: " + deployment.getWorkflowId());

        } catch (Exception e) {
            e.printStackTrace();
        }

Something seems to go wrong with serialisation on the server side, resulting in the following error:

10:26:01.224 [qtp739333799-20 - /deploy] ERROR c.e.server.DefaultExceptionMapper - Exception in Effektif server: java.lang.RuntimeException: Error reading protected java.util.List com.effektif.workflow.api.workflow.Scope.activities: Unknown subclass type ‘scriptTask’ of class com.effektif.workflow.api.workflow.Activity
java.lang.RuntimeException: java.lang.RuntimeException: Error reading protected java.util.List com.effektif.workflow.api.workflow.Scope.activities: Unknown subclass type ‘scriptTask’ of class com.effektif.workflow.api.workflow.Activity
	at com.effektif.workflow.impl.json.JsonStreamMapper.read(JsonStreamMapper.java:83) ~[classes/:na]
	at com.effektif.workflow.impl.json.JsonStreamMapper.read(JsonStreamMapper.java:72) ~[classes/:na]
	at com.effektif.server.EffektifJsonProvider.readFrom(EffektifJsonProvider.java:65) ~[classes/:na]
	at 
<zip.....>
Caused by: java.lang.RuntimeException: Error reading protected java.util.List com.effektif.workflow.api.workflow.Scope.activities: Unknown subclass type ‘scriptTask’ of class com.effektif.workflow.api.workflow.Activity
<zip.....>

I added the following annotations in ScriptTask.java at line 24, like:

>@TypeName("scriptTask")
>@BpmnElement("scriptTask")
>@BpmnTypeAttribute(attribute="type", value="script")

**Comment by hilton** [comment]
The first thing to check is whether the script task is registered as an activity type, by adding its implementation class’s fully-qualified class name (e.g. `com.example.effektif.ScriptTaskImpl`) as a line in a `META-INF/services/com.effektif.workflow.impl.activity.ActivityType ` file in the classpath. We’ve started documenting this in [Custom activity types](https://github.com/effektif/effektif/wiki/Custom-activity-types).

**Comment by jblankendaal** [comment]
Thanks, that worked! 
I didnt even need to add the 
> @BpmnTypeAttribute(attribute="type", value="script")

attribute.

The Custom activity types documentation is very usefull! Do you also already have documentation for the Adapter Activity (propably similar, but I don't get how to register the activity, do I need to start my own AdapterServer, like is done in com.effektif.adapter.test.AdapterTest?)

**Comment by hilton** [comment]
I haven’t documented the Adapter activity yet, but that’s definitely on the to-do list. It just isn’t at the top yet…

**Comment by tombaeyens** [comment]
if you get stuck, i ll answer your questions in the gitter chat.  then peter promised on all the whiskey in the world to listen in and build the adapter docs from there :)

**Comment by jblankendaal** [comment]
Great, hopefully today, otherwise I will work on it tomorrow!

**Comment by jblankendaal** [comment]
The ScriptTask works nicely, but when I want to get a return value of the script via the REST api the return value is empty. See this code:

    public static void main(String[] args) {
        try {

            // Create a workflow
            ExecutableWorkflow workflow = new ExecutableWorkflow()
                    .variable("n", new TextType())
                    .variable("m", new TextType())
                    .activity("s", new ScriptTask()
                            .script("message = 'Hello ' + name;")
                            .scriptMapping("name", "n")
                            .scriptMapping("message", "m"));

            final String url = "http://localhost:9999/";

            ClientConfig clientConfig = new ClientConfig();
            JsonStreamMapper jsonStreamMapper = new JsonStreamMapper();
            clientConfig.register(new EffektifJsonProvider(jsonStreamMapper));
            Client client = ClientBuilder.newClient(clientConfig);

            WebTarget target = client.target(url);
            Deployment deployment =
                    target.path("deploy").request()
                            .accept(MediaType.APPLICATION_JSON)
                            .post(Entity.entity(workflow, MediaType.APPLICATION_JSON))
                            .readEntity(Deployment.class);

            System.out.println("Deployed: " + deployment.getWorkflowId());


            TriggerInstance start = new TriggerInstance()
                    .workflowId(deployment.getWorkflowId())
                    .data("n", "World");

            WorkflowInstance workflowInstance = target.path("start").request()
                    .post(Entity.entity(start, MediaType.APPLICATION_JSON))
                    .readEntity(WorkflowInstance.class);

            System.out.println("Value of m is: " + workflowInstance.getVariableValue("m"));
            // This returns null

        } catch (Exception e) {
            e.printStackTrace();
        }

But if I set isAsync to false in the ScriptTaskImpl, it all works as expected, which makes sense.

Question is: why is the ScriptTask asynchronous by default, and/or is it possible to set it synchronous in the process definition?

**Comment by hilton** [comment]
All tasks are asynchronous so that the process engine never blocks a thread, which is essential for platform scalability. In the case of a script task, it’s just the same as a human task: the task won’t be completed instantly, however much faster the computers are than the humans, so you have to wait.

**Comment by tombaeyens** [comment]
it depends...  not all tasks are async.  an activity implementation can decide if it is executed asynchronous.  java script activity should be asynchronous because javascripts may take a couple of seconds.  during that time we don't want to block the thread of the client.  so that's why JavaScript activities should be async.

In case you implement usertask, those should be synchronous.  well... this means that creation of the task when the flow arrives in a usertask activity should be done synchronous.  after the task is created, the thread of the client returns.  this is done because then all tasks are created and inserted when a workflow instance starts.

**Comment by pfolthof** [comment]
Maybe the question gets easier with an example:

[Event with data field x and y] -> [Script calculating complex formula using x and y, output is z] -> [Exclusive gateway that needs z to determine which path to choose]

In this case we need the Script task to be synchronous as otherwise the gateway would not be able to use the outcome of the calculation.

Hence the question how / where we should change the isAsync flag e.g. in the BPMN, in the class, ... ?

**Comment by tombaeyens** [comment]
If an activity of the workflow is performed asynchronous, the flow will not take the transition until the asynchronous activity is completed.

**Comment by jblankendaal** [comment]
Ok, that clears things up. So back to my 2nd code example: if you do a "start" or "message" of a ScriptTask, you should not expect the results of that executed script back via the returned workflowInstance object. And the script is executed async.
Time to close this issue :-)
About the AdapterActivity: We have it running, I wrote a quick "manual/overview" of it, if you are interested let me know.
