### ISSUE TITLE
Store workflow state

### ISSUE THREAD

**Issue by jblankendaal** [effektif/effektif#36]
After working with Effektif for a while now we're pretty happy, except for one big thing, and that is figuring out in Mongo in what activityId a workflowInstance is.

To find out in what open activityId an instance is, the following query is needed:
```
workflowInstances.find({"activityInstances" : { $elemMatch : { activityId : "xxx", end : { $exists : true }}}}, { "activityInstances.$" : 1 })
```
But when doing aggregations (reporting) or trying to find out in what activityId a workflowInstance is when the flow is ended (you'll have to look at the last entry of the activityInstances array, again a problem in the aggregation framework) is a pain in the (...)

So my proposal is to introduce an array on the top level in workflowInstances containing the current (=last) states a workflowInstance is in (an array because when using a parallel gateway one workflowInstance can actually have 2 or more states it is in)

For example, the json of this array would look like this:
```
    "currentActivityIds" : [ 
        {
            "activityId" : "WaitingForUserInput"
        }, 
        {
            "activityId" : "timedOut"
        }
    ],
```
if the workflowInstance is in two activityId states.

Querying would become easy: 
```
workflowInstances.find({ "currentActivityIds.activityId" : "xxx"}) 
```

The activityInstances array would still exist, but more as history.

Any comments or other (better) ideas are welcome.

**Comment by tombaeyens** [comment]
Looks like a reasonable request to me.  Might become useful for ourselves at some point as well.

I'ld use a list of strings for the activityIds: `{ "WaitingForUserInput", "timedOut" }`  Then you can also do the same query with the `$in` operator.

**Comment by jblankendaal** [comment]
Great, we have that code running already for some time, see #38 for the pull request.

**Comment by jblankendaal** [comment]
It seems even possible to query the array like this : 
```
workflowInstances.find({ currentActivities : "timedOut" })
```
if you are only looking for one currentActivity. Nice

**Comment by tombaeyens** [comment]
You show the right way to do it.  Actually my `$in` suggestion is is wrong.  $in is only to be used if you want to match the value in the mongo json document with many possible options.

**Comment by tombaeyens** [comment]
> Okay - I guess I need to figure out the tricky query that it replaces
The the commit - jblankendaal/effektif@fe37b0e - I’m not sure about the implications of WorkflowInstanceImpl.currentActivityIds having type Set<ActivityInstanceImpl>
i.e. a set of the instances instead of a set of their IDs
I wonder how that serialises
Also, I don't have a warm fuzzy feeling about introducing a new field into the model with no documentation
tombaeyens 10:05
ok. i ll look into it
it should serialize to a set of object ids
that s the main part

> I guess a summary of the discussion at effektif/effektif#36 belongs as a documentation comment on the new field

**Comment by tombaeyens** [comment]
I ll have a look and fix if necessary so that we get a list of strings as the currentActivityIds

**Comment by jblankendaal** [comment]
It actually returns a list of strings, the json representation is for example:
```
"currentActivities" : [  "WaitingForUserInput", "timedOut" ]
```

Hope that helps. 
Also, if I can contribute documenting it better, just let me know the format you want it documented in.

**Comment by tombaeyens** [comment]
@jblankendaal I renamed to openActivityIds and changed the impl a bit.  let me know if this poses a problem for you

**Comment by jblankendaal** [comment]
@tombaeyens The rename is a good idea, I was actually looking for a better name but couldn't come up with one...
You also changed the location in the code where the activityId was removed from the openActivityIds list. This does pose a problem for us with a parallel gateway, since the workflowInstance that is waiting to be joined has its end date already filled in, so does not show up in openActivityIds, but we do need it to show up.
Two possible solutions as far as I am concerned:
1) If a workflowInstance gets state "joining" the end date should not be set, Arguably the best solution because technically it is not finished there
2) Move the remove from openActivityIds back to the location were I had it, but then the name openActivityIds does not make sense anymore :-)
There is actually a 3) and that is that you don't care and leave it where you have it because thats the way you need it in your product.
A workflow example is here, notice the numbers next to the activities, especially the one next to the merging parallel gateway (waiting to be joined with a workflowInstance that is in the UserTask).
<img width="1071" alt="screen shot 2015-09-26 at 21 21 57" src="https://cloud.githubusercontent.com/assets/11930623/10119377/f336a730-6494-11e5-9ed6-cbc9870c1f66.png">

**Comment by tombaeyens** [comment]
I'm open to model it in different ways but currently the auto-firing of depends on the activity instances being closed. 

Take the next  process with 3 simple activities in parallel.  The middle one could arrive at the end event in which only 2 joining activity instances will be created.  In that case the second one has to know it is the last one even when there are 3 incoming transitions.  This is handled by checking 'Is there more work to be done?'.  Which is implemented as 'Are there still open activity instances?'

![screen shot 2015-09-28 at 08 29 33](https://cloud.githubusercontent.com/assets/944245/10129198/c81051f0-65bb-11e5-854a-8df3b3e9860f.png)

**Comment by tombaeyens** [comment]
I may have a solution by taking the joining into account when deciding to auto-fire a joining parallel gateway.  Investigating...

**Comment by tombaeyens** [comment]
Conclusion: might be possible to get it done somehow, but it takes more time then i can currently spend on it.  The path to explore further is this: 1) change the ParallelGatewayImpl as indicated below.  This means only setting the state to `joining` when an activity instance arrives.  And ending the otherJoiningActivityInstances when the joining parallel gateway fires.  Also the check for hasOtherUnfinishedActivities needs to be adjusted accordingly.

Other places that will be impacted:
* ScopeInstanceImpl.hasOpenActivityInstances()
* ScopeInstanceImpl.activityInstanceEnded
* Tests that express the expected open activity instances need to be changed and the joining gateways need to be added.

Changed ParallelGatewayImpl:
```
  @Override
  public void execute(ActivityInstanceImpl activityInstance) {
    activityInstance.setJoining();
    boolean hasOtherUnfinishedActivities = false;

    List<ActivityInstanceImpl> otherJoiningActivityInstances = new ArrayList<>();
    for (ActivityInstanceImpl siblingActivityInstance: activityInstance.parent.activityInstances) {
      if (!siblingActivityInstance.isEnded()
          && !siblingActivityInstance.isJoining()) {
        hasOtherUnfinishedActivities = true;
      }
      
      if ( siblingActivityInstance!=activityInstance
           && siblingActivityInstance.getActivity()==activityInstance.getActivity()
           && siblingActivityInstance.isJoining() ) {
        otherJoiningActivityInstances.add(siblingActivityInstance);
      }
    }
    
    if ( !hasOutgoingTransitions ) {
      activityInstance.end();
      activityInstance.propagateToParent();
    
    } else if ( otherJoiningActivityInstances.size()==(nbrOfIncomingTransitions-1)
                || !hasOtherUnfinishedActivities
              ) {
      if (log.isDebugEnabled()) log.debug("Firing parallel gateway");
      for (ActivityInstanceImpl otherJoiningActivityInstance: otherJoiningActivityInstances) {
        otherJoiningActivityInstance.end();
        activityInstance.removeJoining(otherJoiningActivityInstance);
      }
      activityInstance.onwards();
    } 
  }
```

**Comment by tombaeyens** [comment]
btw, I don't have anything to say about your requirements, but still i'm going to do it :)  I think your users may not be as interested as you think in the number of open joining parallel gateways.  They are typically only interested in the number of real activities that are open.  So consider if not solving this is a good resolution for this issue for you.

**Comment by jblankendaal** [comment]
To close the issue: I solved it in a custom class in our project implementing WorkflowExecutionListener. The transition method is the only method implemented and looks like this:

```java

    @Override
    public boolean transitioning(ActivityInstanceImpl activityInstance, TransitionImpl transition, ActivityInstanceImpl activityInstance1) {
        List<String> lastActivityIds = (List<String>) activityInstance.workflowInstance.getProperty(CpFields.LastActivityIds);

        if (lastActivityIds == null) {
            lastActivityIds = new ArrayList<>();
            activityInstance.workflowInstance.setProperty(CpFields.LastActivityIds, lastActivityIds);
        }

        lastActivityIds.remove(activityInstance.getActivity().getId());

        if (activityInstance1 != null && !lastActivityIds.contains(activityInstance1.getActivity().getId()))
            lastActivityIds.add(activityInstance1.getActivity().getId());

        activityInstance.workflowInstance.setProperty(CpFields.LastActivityIds, lastActivityIds);

        return true;
    }
```
