### ISSUE TITLE
maven issue 

### ISSUE THREAD

**Issue by EivanRazgriz** [effektif/effektif#4]
Hello Effektif Team,

I'm a student at the University of Bamberg and am currently working on a Projekt from our Distributed Systems group in which we check current BPMN engines for BPMN Standard conformity and correctness. So in order to get an understanding of the Effektif engine I was trying to go through the Tutorial and hit a roadblock right at the installation. 
I cloned the project from the git repo then tried to do a "mvn clean install" but I get compilation errors.
I included a screencap of the output (the error list goes on for about 400 lines with the same message about not being able to find symbols, but I think you get the idea)

![mavenoutput](https://cloud.githubusercontent.com/assets/8036386/6691272/ec041522-ccc5-11e4-8fa0-6360bc815d3d.JPG)

**Comment by vijaykiran** [comment]
Can you gist your mvn command output ? 

I just tried a clean `mvn clean install -DskipTests` and it had no errors

**Comment by pepite** [comment]
Which JDK are you using?

On 17 March 2015 at 17:20, Vijay Kiran <notifications@github.com> wrote:

> Can you gist your mvn command output ?
>
> I just tried a clean mvn clean install -DskipTests and it had no errors
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/effektif/effektif/issues/4#issuecomment-82442961>.
>



-- 
Nicolas Leroux

**Comment by tombaeyens** [comment]
this is to do with one of the optional components: a rhino native javascript engine.

the pom files says this: 

```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <encoding>UTF-8</encoding>
          <source>1.7</source>
          <target>1.7</target>
          <compilerArguments>
            <!-- This is to get the Rhino internal classes compiled -->
            <bootclasspath>${java.home}/lib/rt.jar</bootclasspath>
          </compilerArguments>
        </configuration>
      </plugin>
```

so indeed it would be interesting to know on which jdk this doesn't work

**Comment by pfolthof** [comment]
The better solution is not to use the internal package. Instead add this dependency to effectif-workflow-impl:

    <dependency>
      <groupId>org.mozilla</groupId>
      <artifactId>rhino</artifactId>
      <version>1.7R3</version>
    </dependency>

and replace sun.org.mozilla.javascript.internal with org.mozilla.javascript in the sources.

**Comment by tombaeyens** [comment]
great suggestion!
i ll fix it in one of the next days

**Comment by pfolthof** [comment]
Cool. I am not sure if this brings any improvements, but it might be a good idea to move to the latest version of Rhino then. I tried to use 1.7R5, but this caused some problems in the unit tests.

**Comment by tombaeyens** [comment]
i ll keep that in mind.  we ll also have to move it into a separate optional package.

another approach that i might try first is to implement the feature we want inside of the standard scripting api.  i want nested json structures to behave like real javascript objects.  also these nested structures have to be resolved dynamically.  that might be a challenge with the standard scripting api where I have to wrap dynamic objects in Maps.  Afaict, rhino supports that you perform `a.b` (instead of `a.get('b')`.  But I recall reading this is rhino specific.  So other javascript engines might not support that.

**Comment by EivanRazgriz** [comment]
Here is the printout from the mvn -v. As you can see this uses the Java 8 Jdk

adding the dependencies seemed to work, but I got a connection reset while trying to download the files. But this is probably a completely different error and most likely has to do with the network in the University.

```
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T18:37:52+01:00)
Maven home: [...]\dsg-project\maven\apache-maven-3.2.1\bin\..
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: [...]\Java\jdk1.8.0_31\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by EivanRazgriz** [comment]
I forgot to add the -DskipTests statement to my maven command, now it worked.
replacing the source files was kind of a hassle though. Thanks for the help
