### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by albertotn** [effektif/effektif#55]
Hi, evaluating effektif for a project and I found really "unhelpful" roadmap page here:

https://github.com/effektif/effektif/wiki/Road-map

Could you please update it ? thanks!

**Comment by hilton** [comment]
Hi @albertotn - sorry about that - we clearly just completely forgot about this page. I think we’ll probably just have to delete it, and then work out what to say about what's next with the project. Thanks for letting us know.

**Comment by albertotn** [comment]
My 2 cents: it's better to have some sort of "vision" on next steps, so people like me can evaluate properly your project direction :+1:

**Comment by hilton** [comment]
I’ve added a [road map summary](https://github.com/effektif/effektif/wiki#road-map) to the bottom of the wiki home page.
