### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by pfolthof** [effektif/effektif#6]
Various articles about Effektif mention it running the JavaScript in node.js. I think that makes sense both in terms of performance and available libraries. However, in both the sources and available documentation I can only find references to Rhino. Could anybody tell me if / how Effektif should be configured to use node.js?

**Comment by tombaeyens** [comment]
It's not yet in the engine codebase.  That s a matter of prioritization.  We opted to start with the JVM JavaScript to minimize the setup hassle.  First we have to ensure that our product gets migrated to the new open source engine.  Once that's done we can start migrating other pieces like the node.js scripting engine.  
Good that you let us know you want it.  So we keep it on the radar.
