### ISSUE TITLE
TypeError in /nochniemandsorganisation/tasks/all

### ISSUE THREAD

**Issue by jfschwarz** [effektif/effektif#8]
## Exception in Effektif

**TypeError** in **/nochniemandsorganisation/tasks/all**
TypeError: this.get(...).getProcess is not a function

[View on Bugsnag](https://bugsnag.com/effektif/effektif/errors/551170df4f563d921e24dccf?event_id=5515f96c8eed97df1c2b6d61)

## Stacktrace

    https://app.effektif.com/effektif.min.js:22 - h&lt;.getProcess
    https://app.effektif.com/effektif.min.js:29 - .renderTasks/o&lt;
    https://app.effektif.com/effektif.min.js:5 - rt/&lt;

[View full stacktrace](https://bugsnag.com/effektif/effektif/errors/551170df4f563d921e24dccf?event_id=5515f96c8eed97df1c2b6d61)

**Comment by frontendphil** [comment]
wrong tracker.
